{
  "formatVersion": "1.1",
  "component": {
    "group": "coder.siy",
    "module": "tenseiga-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "tenseiga-plugin-1.0.0.jar",
          "url": "tenseiga-plugin-1.0.0.jar",
          "size": 135554,
          "sha512": "03d3894c70235cb0064e9e51e54ec10a5cf3439cfb4d6801dfb18e03c81fe6ca0521b4e3911690c261de877eee4202d6519536522a2319be1009771353e95554",
          "sha256": "46de01b24e5fdf7523a2b21457eb6ebb8120e2c502585e5e79fdcf99284eee16",
          "sha1": "7b881d4c0dda4fe1ac0d508dbc4173b08bbd7de3",
          "md5": "fc045d29b09c3a968990d6b395243c19"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.5.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-gradle-plugin",
          "version": {
            "requires": "5.0.0-rc1"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-api",
          "version": {
            "requires": "5.0.0-rc1"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-asm",
          "version": {
            "requires": "5.0.0-rc1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "tenseiga-plugin-1.0.0.jar",
          "url": "tenseiga-plugin-1.0.0.jar",
          "size": 135554,
          "sha512": "03d3894c70235cb0064e9e51e54ec10a5cf3439cfb4d6801dfb18e03c81fe6ca0521b4e3911690c261de877eee4202d6519536522a2319be1009771353e95554",
          "sha256": "46de01b24e5fdf7523a2b21457eb6ebb8120e2c502585e5e79fdcf99284eee16",
          "sha1": "7b881d4c0dda4fe1ac0d508dbc4173b08bbd7de3",
          "md5": "fc045d29b09c3a968990d6b395243c19"
        }
      ]
    }
  ]
}
