{
  "formatVersion": "1.1",
  "component": {
    "group": "coder.siy",
    "module": "tenseiga-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "tenseiga-plugin-1.0.0.jar",
          "url": "tenseiga-plugin-1.0.0.jar",
          "size": 135181,
          "sha512": "ebc81fbdb34ff312107f868d5c7a7ce9f368b10100e24533ec9e48826e840aba5762963af173ff99838b60d61811f879b1d6e1f5c4a76d18ecbf9d20876d908e",
          "sha256": "049175f7523b05dfdf727b80f2a81f66cf3fc0a12ae14ede63160e4b1dcea013",
          "sha1": "fa8566b05864172f5ff7c17b8ff4267a40410334",
          "md5": "fdfa0a8c33b4288902ab0f56412c609a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "8.5.0"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-api",
          "version": {
            "requires": "5.0.0-rc1"
          }
        },
        {
          "group": "com.didiglobal.booster",
          "module": "booster-transform-asm",
          "version": {
            "requires": "5.0.0-rc1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.22"
          }
        }
      ],
      "files": [
        {
          "name": "tenseiga-plugin-1.0.0.jar",
          "url": "tenseiga-plugin-1.0.0.jar",
          "size": 135181,
          "sha512": "ebc81fbdb34ff312107f868d5c7a7ce9f368b10100e24533ec9e48826e840aba5762963af173ff99838b60d61811f879b1d6e1f5c4a76d18ecbf9d20876d908e",
          "sha256": "049175f7523b05dfdf727b80f2a81f66cf3fc0a12ae14ede63160e4b1dcea013",
          "sha1": "fa8566b05864172f5ff7c17b8ff4267a40410334",
          "md5": "fdfa0a8c33b4288902ab0f56412c609a"
        }
      ]
    }
  ]
}
